### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by hpurmann** [alangpierce/bulk-decaffeinate#67]
I cannot install bulk-decaffeinate on my machine. Using nvm with node 6.9.1, macOS `10.12.2`. Tried with `npm` and `yarn`.

What's wrong here?

```
➜ npm install -g bulk-decaffeinate
/Users/hpurmann/.nvm/versions/node/v6.9.1/bin/bulk-decaffeinate -> /Users/hpurmann/.nvm/versions/node/v6.9.1/lib/node_modules/bulk-decaffeinate/bin/bulk-decaffeinate

> nodegit@0.16.0 install /Users/hpurmann/.nvm/versions/node/v6.9.1/lib/node_modules/bulk-decaffeinate/node_modules/nodegit
> node lifecycleScripts/preinstall && node lifecycleScripts/install

[nodegit] Running pre-install script
[nodegit] Configuring libssh2.
{ Error: Command failed: /Users/hpurmann/.nvm/versions/node/v6.9.1/lib/node_modules/bulk-decaffeinate/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/Users/hpurmann/.nvm/versions/node/v6.9.1/lib/node_modules/bulk-decaffeinate/node_modules/nodegit/vendor/openssl/openssl
/Users/hpurmann/.nvm/versions/node/v6.9.1/lib/node_modules/bulk-decaffeinate/node_modules/nodegit/vendor/libssh2/missing: Unknown `--is-lightweight' option
Try `/Users/hpurmann/.nvm/versions/node/v6.9.1/lib/node_modules/bulk-decaffeinate/node_modules/nodegit/vendor/libssh2/missing --help' for more information
configure: WARNING: 'missing' script is too old or missing
configure: error: No crypto library found!
Try --with-libssl-prefix=PATH
 or --with-libgcrypt-prefix=PATH
 or --with-wincng on Windows

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: '/Users/hpurmann/.nvm/versions/node/v6.9.1/lib/node_modules/bulk-decaffeinate/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/Users/hpurmann/.nvm/versions/node/v6.9.1/lib/node_modules/bulk-decaffeinate/node_modules/nodegit/vendor/openssl/openssl' }
/Users/hpurmann/.nvm/versions/node/v6.9.1/lib/node_modules/bulk-decaffeinate/node_modules/nodegit/vendor/libssh2/missing: Unknown `--is-lightweight' option
Try `/Users/hpurmann/.nvm/versions/node/v6.9.1/lib/node_modules/bulk-decaffeinate/node_modules/nodegit/vendor/libssh2/missing --help' for more information
configure: WARNING: 'missing' script is too old or missing
configure: error: No crypto library found!
Try --with-libssl-prefix=PATH
 or --with-libgcrypt-prefix=PATH
 or --with-wincng on Windows

[nodegit] ERROR - Could not finish preinstall
{ Error: Command failed: /Users/hpurmann/.nvm/versions/node/v6.9.1/lib/node_modules/bulk-decaffeinate/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/Users/hpurmann/.nvm/versions/node/v6.9.1/lib/node_modules/bulk-decaffeinate/node_modules/nodegit/vendor/openssl/openssl
/Users/hpurmann/.nvm/versions/node/v6.9.1/lib/node_modules/bulk-decaffeinate/node_modules/nodegit/vendor/libssh2/missing: Unknown `--is-lightweight' option
Try `/Users/hpurmann/.nvm/versions/node/v6.9.1/lib/node_modules/bulk-decaffeinate/node_modules/nodegit/vendor/libssh2/missing --help' for more information
configure: WARNING: 'missing' script is too old or missing
configure: error: No crypto library found!
Try --with-libssl-prefix=PATH
 or --with-libgcrypt-prefix=PATH
 or --with-wincng on Windows

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: '/Users/hpurmann/.nvm/versions/node/v6.9.1/lib/node_modules/bulk-decaffeinate/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/Users/hpurmann/.nvm/versions/node/v6.9.1/lib/node_modules/bulk-decaffeinate/node_modules/nodegit/vendor/openssl/openssl' }
/Users/hpurmann/.nvm/versions/node/v6.9.1/lib
└── (empty)

npm ERR! Darwin 16.3.0
npm ERR! argv "/Users/hpurmann/.nvm/versions/node/v6.9.1/bin/node" "/Users/hpurmann/.nvm/versions/node/v6.9.1/bin/npm" "install" "-g" "bulk-decaffeinate"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE

npm ERR! nodegit@0.16.0 install: `node lifecycleScripts/preinstall && node lifecycleScripts/install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nodegit@0.16.0 install script 'node lifecycleScripts/preinstall && node lifecycleScripts/install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the nodegit package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node lifecycleScripts/preinstall && node lifecycleScripts/install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs nodegit
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls nodegit
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/hpurmann/dev/actano/rplan/npm-debug.log
npm ERR! code 1
```

**Comment by alangpierce** [comment]
Yikes, thanks for reporting. I have the same node and macOS version as you and unfortunately can't reproduce. The issue here is it's trying to install the nodegit dependency, but that's failing due to a binary dependency that it's trying to pull in. Looks like this issue might have some useful info: https://github.com/nodegit/nodegit/issues/1134

Can you try `sudo xcode-select --install` (mentioned in that issue) and let me know if that fixes things? (I think it just installs the xcode command line tools if they're not already installed.)

Also, can you tell me what version of the xcode command line tools you have (if they're installed)? Looks like you can use `pkgutil --pkg-info=com.apple.pkg.CLTools_Executables` to do that. I get version 8.2.0.0.1.1480973914.

**Comment by hpurmann** [comment]
Nice, this works! Thank you a lot 👍
